microscope: simulate
camera: simulate
calibration: simulate

data_directory: C:/instamatic
#flatfield: C:/instamatic/flatfield.tiff
flatfield: 

use_tem_server: True
tem_server_host: 'localhost'
tem_server_port: 8088

use_cam_server: False
cam_server_host: 'localhost'
cam_server_port: 8087

indexing_server_exe: 'instamatic.dialsserver.exe'
indexing_server_host: 'localhost'
indexing_server_port: 8089

fei_server_host: '192.168.12.1'
fei_server_port: 9999

dials_script: 'E:/cctbx/dials_script.bat'

cred_relax_beam_before_experiment: false
cred_track_stage_positions: false

modules:
  - 'cred'
  - 'cred_tvips'
  - 'cred_fei'
  - 'sed'
  - 'autocred'
  - 'red'
  - 'machine_learning'
  - 'ctrl'
  - 'debug'
  - 'about'
  - 'io'
